version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_sc_g10
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
    networks:
      - backend

  web:
    build: app/
    image: ecommerce_image_g10
    container_name: ecommerce_image_g10
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app
      - FLASK_ENV=development
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge